/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 18 13:40:53 GMT 2019
 */

package com.program.backend.web;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import com.program.backend.service.CommentService;
import com.program.backend.web.CommentController;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CommentController_ESTest extends CommentController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CommentController commentController0 = new CommentController();
      CommentService commentService0 = mock(CommentService.class, new ViolatedAssumptionAnswer());
      Injector.inject(commentController0, (Class<?>) CommentController.class, "commentService", (Object) commentService0);
      Injector.validateBean(commentController0, (Class<?>) CommentController.class);
  }
}
