/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 18 13:41:33 GMT 2019
 */

package com.program.backend.web;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import com.program.backend.service.PetService;
import com.program.backend.web.PetController;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PetController_ESTest extends PetController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PetController petController0 = new PetController();
      PetService petService0 = mock(PetService.class, new ViolatedAssumptionAnswer());
      Injector.inject(petController0, (Class<?>) PetController.class, "petService", (Object) petService0);
      Injector.validateBean(petController0, (Class<?>) PetController.class);
  }
}
